import type { Stock, RegimeData } from "@/lib/types";

export { type Stock, type RegimeData };

export const mockRegime: RegimeData = {
  status: "BEARISH",
  spyPrice: 558.00,
  sma200: 539.50,
  sma50: 555.20,
  spyRsi: 42.5,
  vix: 24.06,
  ratio: 1.034,
  regimeScore: 1,
};

export const mockStocks: Stock[] = [
  // ── Under $10 ───────────────────────────────────────────────────────
  {
    ticker: "PLUG", name: "Plug Power Inc", tradeType: "SHORT", bullScore: 2, bearScore: 5, price: 2.40, rsi: 38.5,
    volumeRatio: 2.1, volumeSpike: true,
    signals: { sma200: true, sma50: true, rsiMomentum: true, volume: true, macd: true, priceAction: false, trendStrength: true, earningsSetup: false },
    entryAtr: 2.55, entryStructure: 2.50, bestEntry: 2.55, stopLoss: 2.85, target: 1.80, riskReward: 2.5, atr: 0.12, distance52w: -62.3,
    conflictTrend: false, earningsWarning: false, updatedAt: "4:15 PM ET",
    news: [
      { title: "PLUG burns $250M cash in Q1, raises going-concern doubts", date: "Apr 28", source: "Bloomberg", summary: "Cash reserves fall to $620M; analysts warn of potential dilutive financing within 12 months.", sentiment: "bearish" },
      { title: "DOE hydrogen hub funding delayed six months", date: "Apr 25", source: "DOE", summary: "Administrative review pushes $500M PLUG-affiliated hub grant to Q4, delaying revenue recognition.", sentiment: "bearish" },
      { title: "Green hydrogen margins remain negative at $-2/kg cost gap", date: "Apr 22", source: "S&P Global", summary: "Electrolyzer operating costs still above $6/kg vs. gray hydrogen at $1.50/kg, squeezing PLUG economics.", sentiment: "bearish" },
      { title: "Amazon reduces PLUG warrant deployment timeline", date: "Apr 20", source: "Reuters", summary: "AMZN scales back forklift hydrogen rollout, reducing PLUG's near-term warrant vesting schedule.", sentiment: "bearish" },
      { title: "EU hydrogen infrastructure investment accelerates", date: "Apr 17", source: "Reuters", summary: "European green hydrogen corridor funding reaches €2B, benefiting PLUG's expanding EU operations.", sentiment: "bullish" },
      { title: "PLUG wins 100MW electrolyzer order in Australia", date: "Apr 14", source: "PRNewswire", summary: "Large-scale green hydrogen project in Queensland marks PLUG's first major APAC supply contract.", sentiment: "bullish" },
    ],
  },
  {
    ticker: "NIO", name: "NIO Inc", tradeType: "LONG", bullScore: 5, bearScore: 3, price: 4.55, rsi: 52.4,
    volumeRatio: 1.8, volumeSpike: true,
    signals: { sma200: false, sma50: true, rsiMomentum: true, volume: true, macd: true, priceAction: true, trendStrength: false, earningsSetup: false },
    entryAtr: 4.30, entryStructure: 4.40, bestEntry: 4.30, stopLoss: 3.90, target: 5.80, riskReward: 3.75, atr: 0.18, distance52w: -28.4,
    conflictTrend: true, earningsWarning: false, updatedAt: "4:15 PM ET",
    news: [
      { title: "NIO deliveries hit 31,000 units in March 2025, monthly record", date: "Apr 27", source: "NIO PR", summary: "ET9 flagship sedan drives ASP above $50K for first time, improving gross margin trajectory.", sentiment: "bullish" },
      { title: "NIO ONVO brand captures 8% of China's $20K EV segment", date: "Apr 24", source: "Bloomberg", summary: "Budget ONVO L60 SUV outsells BYD's Seal U in comparable price bracket for second consecutive month.", sentiment: "bullish" },
      { title: "Battery-as-a-Service swap stations reach 2,500 globally", date: "Apr 21", source: "NIO IR", summary: "BaaS network moat widens as competitors struggle to replicate standardized swap infrastructure.", sentiment: "bullish" },
      { title: "China EV price war intensifies; BYD cuts prices 8%", date: "Apr 19", source: "Reuters", summary: "BYD's aggressive discounting forces margin compression across entire Chinese EV market.", sentiment: "bearish" },
      { title: "NIO reports Q1 gross margin of 9.2%, beating 8% estimate", date: "Apr 16", source: "Bloomberg", summary: "Software and services revenue growth offsets lower vehicle margin pressure from ONVO pricing.", sentiment: "bullish" },
      { title: "US tariff risk limits NIO's international expansion timeline", date: "Apr 13", source: "FT", summary: "100% EV tariffs block NIO from targeting European markets from Chinese production base.", sentiment: "bearish" },
    ],
  },
  {
    ticker: "SOFI", name: "SoFi Technologies Inc", tradeType: "LONG", bullScore: 6, bearScore: 2, price: 8.10, rsi: 58.3,
    volumeRatio: 1.6, volumeSpike: false,
    signals: { sma200: false, sma50: true, rsiMomentum: true, volume: true, macd: true, priceAction: true, trendStrength: true, earningsSetup: false },
    entryAtr: 7.80, entryStructure: 7.90, bestEntry: 7.80, stopLoss: 7.20, target: 9.80, riskReward: 3.17, atr: 0.22, distance52w: 42.1,
    conflictTrend: false, earningsWarning: false, updatedAt: "4:15 PM ET",
    news: [
      { title: "SoFi members surpass 10M milestone, 34% YoY growth", date: "Apr 29", source: "SOFI IR", summary: "Member acquisition costs fall 18% as referral loops and Galileo fintech-as-a-service flywheel accelerate.", sentiment: "bullish" },
      { title: "SoFi Bank NIM expands to 5.9% vs. big-bank average of 2.8%", date: "Apr 26", source: "Bloomberg", summary: "Digital-only model keeps deposit gathering costs low while high-yield savings attract rate-sensitive customers.", sentiment: "bullish" },
      { title: "Galileo processes $1T in annualized payment volume", date: "Apr 23", source: "PRNewswire", summary: "B2B fintech infrastructure unit now serves 150 clients including crypto exchanges and challenger banks.", sentiment: "bullish" },
      { title: "Student loan refinancing volume rebounds 40% YoY", date: "Apr 20", source: "SOFI IR", summary: "Post-pause borrower activity and income-share agreements drive SOFI's highest-margin lending product higher.", sentiment: "bullish" },
      { title: "First-loss credit risk remains elevated on personal loans", date: "Apr 17", source: "Reuters", summary: "Net charge-off rate of 3.8% on personal loan book raises concern about underwriting standards at scale.", sentiment: "bearish" },
      { title: "Morgan Stanley initiates SOFI at Overweight, $12 target", date: "Apr 14", source: "Morgan Stanley", summary: "Bank charter leverage, member density, and cross-sell economics support path to $2 EPS by 2027.", sentiment: "bullish" },
    ],
  },
  {
    ticker: "MARA", name: "Marathon Digital Holdings", tradeType: "LONG", bullScore: 5, bearScore: 3, price: 7.45, rsi: 55.8,
    volumeRatio: 2.4, volumeSpike: true,
    signals: { sma200: false, sma50: true, rsiMomentum: true, volume: true, macd: true, priceAction: false, trendStrength: false, earningsSetup: false },
    entryAtr: 7.10, entryStructure: 7.20, bestEntry: 7.10, stopLoss: 6.40, target: 9.50, riskReward: 3.43, atr: 0.35, distance52w: -44.8,
    conflictTrend: true, earningsWarning: false, updatedAt: "4:15 PM ET",
    news: [
      { title: "MARA hash rate reaches 50 EH/s, largest public miner globally", date: "Apr 28", source: "Marathon IR", summary: "Scale advantage lowers production cost per BTC to $34,500, well below current market price.", sentiment: "bullish" },
      { title: "Bitcoin holds $95,000 support after ETF inflow acceleration", date: "Apr 25", source: "Bloomberg", summary: "Spot BTC ETFs record $800M weekly inflows; mining stocks levered 3x to BTC price moves.", sentiment: "bullish" },
      { title: "MARA hedges 30% of 2025 BTC production at $92K via collars", date: "Apr 22", source: "PRNewswire", summary: "Structured downside protection locks in breakeven economics while maintaining upside participation.", sentiment: "bullish" },
      { title: "Electricity costs rise 12% in MARA's Texas facilities", date: "Apr 20", source: "Reuters", summary: "ERCOT grid tightness pushes power purchase agreements to record highs, compressing miner margins.", sentiment: "bearish" },
      { title: "SEC requires enhanced disclosure on BTC treasury accounting", date: "Apr 17", source: "SEC.gov", summary: "New ASC 820 fair value rules force MARA to mark-to-market BTC holdings, adding P&L volatility.", sentiment: "bearish" },
      { title: "MARA acquires 2 data centers for $180M to reduce lease exposure", date: "Apr 14", source: "Business Wire", summary: "Owned infrastructure reduces operating cost by $0.015/kWh vs. third-party hosting agreements.", sentiment: "bullish" },
    ],
  },
  {
    ticker: "VALE", name: "Vale S.A.", tradeType: "LONG", bullScore: 4, bearScore: 2, price: 9.20, rsi: 50.1,
    volumeRatio: 1.2, volumeSpike: false,
    signals: { sma200: false, sma50: true, rsiMomentum: false, volume: false, macd: true, priceAction: true, trendStrength: false, earningsSetup: false },
    entryAtr: 8.90, entryStructure: 9.00, bestEntry: 8.90, stopLoss: 8.30, target: 11.00, riskReward: 3.5, atr: 0.22, distance52w: -32.5,
    conflictTrend: false, earningsWarning: false, updatedAt: "4:15 PM ET",
    news: [
      { title: "Vale iron ore quarterly output hits 90M tonnes, 5-year high", date: "Apr 27", source: "Vale IR", summary: "S11D Eliezer Batista complex achieves nameplate capacity; unit cash cost falls to $17.50/t.", sentiment: "bullish" },
      { title: "China steel output rises 4% MoM on infrastructure stimulus", date: "Apr 24", source: "NBS China", summary: "Beijing's $1T infrastructure bond program drives rebar and HRC demand, supporting iron ore prices at $105/t.", sentiment: "bullish" },
      { title: "Vale base metals unit spun off, unlocks EV supply chain value", date: "Apr 21", source: "Bloomberg", summary: "Nickel and copper mining subsidiarity IPO valued at $26B, crystallizing $8B in value above book.", sentiment: "bullish" },
      { title: "Brumadinho dam settlement payments continue through 2026", date: "Apr 18", source: "Reuters", summary: "Remaining $4.5B in reparations tied to court milestones; cash outflow constrains buyback capacity.", sentiment: "bearish" },
      { title: "Iron ore price falls 8% on Dalian futures market", date: "Apr 15", source: "FT", summary: "Slower Chinese property completions and inventory buildup at Qingdao port drive near-term price weakness.", sentiment: "bearish" },
      { title: "Vale dividend yield reaches 9.2% at current price", date: "Apr 12", source: "Bloomberg", summary: "Semi-annual declare of $0.42/ADR against $9.20 price offers rare value in mining sector.", sentiment: "bullish" },
    ],
  },
  {
    ticker: "F", name: "Ford Motor Company", tradeType: "LONG", bullScore: 4, bearScore: 2, price: 9.80, rsi: 48.6,
    volumeRatio: 1.4, volumeSpike: false,
    signals: { sma200: false, sma50: true, rsiMomentum: false, volume: false, macd: true, priceAction: true, trendStrength: false, earningsSetup: false },
    entryAtr: 9.50, entryStructure: 9.60, bestEntry: 9.50, stopLoss: 8.90, target: 11.50, riskReward: 3.33, atr: 0.28, distance52w: -28.4,
    conflictTrend: false, earningsWarning: false, updatedAt: "4:15 PM ET",
    news: [
      { title: "Ford Pro commercial van segment posts $2.1B EBIT, 12% margin", date: "Apr 28", source: "Ford IR", summary: "Transit Connectand Super Duty demand from small businesses drives Ford's most profitable unit higher.", sentiment: "bullish" },
      { title: "Ford F-150 Lightning production normalized after battery recall", date: "Apr 25", source: "Reuters", summary: "All 14,000 recalled units remedied; Dearborn assembly line returns to 2,200/week rate ahead of schedule.", sentiment: "bullish" },
      { title: "Ford EV division Model e narrows full-year loss to $3.8B", date: "Apr 22", source: "Bloomberg", summary: "Better-than-feared EV metrics raise hopes for near-breakeven by 2027 without additional restructuring.", sentiment: "bullish" },
      { title: "UAW contract costs add $900M annually through 2027", date: "Apr 19", source: "FT", summary: "28% wage increase settlement increases per-vehicle labor cost by $850, pressuring ICE margin.", sentiment: "bearish" },
      { title: "Ford Mexico plants face tariff uncertainty risk", date: "Apr 16", source: "Reuters", summary: "Potential 25% USMCA tariff on Mexican-built vehicles threatens Maverick and Bronco Sport economics.", sentiment: "bearish" },
      { title: "Ford's new BlueOval SK battery joint venture achieves commercial operation", date: "Apr 13", source: "PRNewswire", summary: "Kentucky gigafactory reaches 35 GWh capacity, securing domestic battery supply for next-gen F-150 Lightning.", sentiment: "bullish" },
    ],
  },
  {
    ticker: "AAL", name: "American Airlines Group", tradeType: "SHORT", bullScore: 2, bearScore: 5, price: 9.45, rsi: 37.2,
    volumeRatio: 1.9, volumeSpike: true,
    signals: { sma200: true, sma50: true, rsiMomentum: true, volume: true, macd: true, priceAction: false, trendStrength: true, earningsSetup: false },
    entryAtr: 9.80, entryStructure: 9.70, bestEntry: 9.80, stopLoss: 10.80, target: 7.50, riskReward: 2.3, atr: 0.32, distance52w: -52.4,
    conflictTrend: false, earningsWarning: false, updatedAt: "4:15 PM ET",
    news: [
      { title: "AAL Q1 revenue misses by 4% on corporate travel softness", date: "Apr 29", source: "Bloomberg", summary: "Business class load factors drop to 68% vs. 78% prior year; credit card NDC migration backfires.", sentiment: "bearish" },
      { title: "American Airlines debt reaches $38B, highest among US carriers", date: "Apr 26", source: "Reuters", summary: "Interest expense consumes 18% of revenue; refinancing risk intensifies as $6B matures in 2026.", sentiment: "bearish" },
      { title: "Jet fuel costs rise 14% QoQ, hedging program only 20% covered", date: "Apr 23", source: "FT", summary: "AAL's minimal fuel hedging leaves it most exposed to oil price spikes among major US airlines.", sentiment: "bearish" },
      { title: "DOT probe into AAL's NDC distribution practices widens", date: "Apr 20", source: "Reuters", summary: "Federal inspection of fare display practices on third-party booking platforms may result in fines.", sentiment: "bearish" },
      { title: "AAL capacity cuts generate revenue per seat improvement", date: "Apr 17", source: "Bloomberg", summary: "5% ASM reduction in Q2 drives PRASM up 3.2% as yield management improves on core routes.", sentiment: "bullish" },
      { title: "American AAdvantage loyalty program valued at $26B by Citigroup", date: "Apr 14", source: "Citigroup Research", summary: "Co-brand card portfolio generates $6B in annual cash, providing backstop for AAL's balance sheet.", sentiment: "bullish" },
    ],
  },
  {
    ticker: "SNAP", name: "Snap Inc", tradeType: "SHORT", bullScore: 2, bearScore: 5, price: 9.60, rsi: 40.1,
    volumeRatio: 1.7, volumeSpike: false,
    signals: { sma200: true, sma50: true, rsiMomentum: false, volume: true, macd: true, priceAction: true, trendStrength: false, earningsSetup: false },
    entryAtr: 10.00, entryStructure: 9.90, bestEntry: 10.00, stopLoss: 11.00, target: 7.80, riskReward: 2.2, atr: 0.28, distance52w: -48.6,
    conflictTrend: false, earningsWarning: false, updatedAt: "4:15 PM ET",
    news: [
      { title: "Snap daily active users growth stalls at 422M, misses forecast", date: "Apr 29", source: "Bloomberg", summary: "DAU growth drops to 3% YoY vs. 9% prior year; Gen Z audience share lost to TikTok and Instagram Reels.", sentiment: "bearish" },
      { title: "Snap revenue guidance cut 8% for Q2 on ad market softness", date: "Apr 26", source: "Reuters", summary: "DR advertising budget shifts accelerate toward Meta and Google; SNAP's direct response ad yield falls.", sentiment: "bearish" },
      { title: "Snap Spectacles AR glasses inventory write-down of $180M", date: "Apr 23", source: "Bloomberg", summary: "Gen 5 hardware disappoints sell-through; company marks down channel inventory and exits retail partnership.", sentiment: "bearish" },
      { title: "SNAP+ subscription reaches 15M paying users", date: "Apr 20", source: "Snap IR", summary: "Premium subscription tier growing 40% YoY provides $250M annualized recurring revenue stream.", sentiment: "bullish" },
      { title: "Creator Marketplace integrations attract 500 SMB advertisers", date: "Apr 17", source: "Adweek", summary: "New camera commerce tools allow try-on and purchase directly in Snaps, boosting e-commerce ad take rates.", sentiment: "bullish" },
      { title: "EU Digital Services Act compliance costs add $80M annually", date: "Apr 14", source: "Reuters", summary: "GDPR and DSA content moderation requirements require 400 new full-time equivalents in Europe.", sentiment: "bearish" },
    ],
  },
  {
    ticker: "NOK", name: "Nokia Oyj", tradeType: "LONG", bullScore: 4, bearScore: 2, price: 4.15, rsi: 51.8,
    volumeRatio: 1.1, volumeSpike: false,
    signals: { sma200: false, sma50: true, rsiMomentum: false, volume: false, macd: true, priceAction: true, trendStrength: false, earningsSetup: false },
    entryAtr: 4.00, entryStructure: 4.05, bestEntry: 4.00, stopLoss: 3.70, target: 5.00, riskReward: 3.33, atr: 0.12, distance52w: -12.5,
    conflictTrend: false, earningsWarning: false, updatedAt: "4:15 PM ET",
    news: [
      { title: "Nokia wins $1B Verizon 5G Open RAN contract extension", date: "Apr 28", source: "Telecom Paper", summary: "Multi-year RAN and core network refresh covers 40,000 sites, cementing NOK's #1 position in US-tier RAN.", sentiment: "bullish" },
      { title: "Nokia IP Routing portfolio wins 12 Tier-1 carrier wins in Q1", date: "Apr 25", source: "Nokia IR", summary: "7750 SR router displaces Cisco in backbone upgrades; IP/Optical now 35% of revenue mix.", sentiment: "bullish" },
      { title: "NOK raises FY25 operating margin guidance to 11-14% from 10-13%", date: "Apr 22", source: "Bloomberg", summary: "Net profit beats consensus by 18%; cost reduction program delivers €200M ahead of schedule.", sentiment: "bullish" },
      { title: "Huawei banned from Nordic 5G upgrades; NOK primary beneficiary", date: "Apr 19", source: "Reuters", summary: "Sweden, Finland, and Denmark mandate Huawei removal from 5G SA core networks, creating $600M TAM for Nokia.", sentiment: "bullish" },
      { title: "Mobile Networks segment faces India pricing pressure", date: "Apr 16", source: "Ovum", summary: "Reliance Jio contract renegotiation compresses average selling prices for macro RAN equipment 12%.", sentiment: "bearish" },
      { title: "NOK dividend raised 8% to €0.13/share for FY25", date: "Apr 13", source: "PRNewswire", summary: "Yield of 3.1% at current price rewards income investors; buyback program adds €300M in additional returns.", sentiment: "bullish" },
    ],
  },
  {
    ticker: "XPEV", name: "XPeng Inc", tradeType: "LONG", bullScore: 5, bearScore: 3, price: 6.30, rsi: 53.4,
    volumeRatio: 2.0, volumeSpike: true,
    signals: { sma200: false, sma50: true, rsiMomentum: true, volume: true, macd: true, priceAction: false, trendStrength: false, earningsSetup: false },
    entryAtr: 6.00, entryStructure: 6.10, bestEntry: 6.00, stopLoss: 5.40, target: 8.20, riskReward: 3.67, atr: 0.25, distance52w: -18.7,
    conflictTrend: true, earningsWarning: false, updatedAt: "4:15 PM ET",
    news: [
      { title: "XPEV X9 MPV deliveries beat expectations at 4,200 units in March", date: "Apr 28", source: "Bloomberg", summary: "Premium MPV priced at $55K captures 22% of China luxury EV minivan market in first full quarter.", sentiment: "bullish" },
      { title: "XPeng XNGP autonomous driving reaches Level 3 certification in China", date: "Apr 25", source: "MIIT", summary: "XPEV first Chinese OEM authorized for eyes-off highway driving; regulatory moat creates brand differentiation.", sentiment: "bullish" },
      { title: "VW joint venture contributes $200M in technology licensing fees", date: "Apr 22", source: "Bloomberg", summary: "Volkswagen EEA platform collaboration generates recurring software royalty stream from 2025.", sentiment: "bullish" },
      { title: "XPEV gross margin improves to 14.2%, exceeds 12% guidance", date: "Apr 19", source: "XPEV IR", summary: "Software monetization from XNGP subscriptions and cost savings from Zhaoqing factory drive margin expansion.", sentiment: "bullish" },
      { title: "BYD's budget Seagull competes directly with XPEV's Mona M03", date: "Apr 16", source: "Reuters", summary: "Seagull's 8% price cut intensifies competition in the 120,000 RMB price band, pressuring XPEV volumes.", sentiment: "bearish" },
      { title: "Short sellers cite XPEV's 24-month delivery volume risk", date: "Apr 13", source: "Hindenburg-style research note", summary: "Bears argue R&D pipeline over-promised; ADAS regulatory approval pace could slip 18 months.", sentiment: "bearish" },
    ],
  },
  // ── Swing Trade Leaders 2026 ──────────────────────────────────────
  {
    ticker: "LMT", name: "Lockheed Martin Corp", tradeType: "SHORT", bullScore: 2, bearScore: 7, price: 455.00, rsi: 36.0,
    volumeRatio: 1.7, volumeSpike: true,
    signals: { sma200: false, sma50: false, rsiMomentum: true, volume: true, macd: true, priceAction: false, trendStrength: true, earningsSetup: true },
    entryAtr: 460.00, entryStructure: 458.00, bestEntry: 460.00, stopLoss: 478.00, target: 420.00, riskReward: 2.22, atr: 8.5, distance52w: -22.4,
    conflictTrend: false, earningsWarning: false, updatedAt: "11:01 PM ET",
    news: [
      { title: "Defense sector under pressure amid budget cuts", date: "Mar 17", source: "Reuters", summary: "Pentagon announces a 5% reduction in procurement spending, hitting major defense contractors including LMT.", sentiment: "bearish" },
      { title: "LMT Q1 earnings miss analyst expectations", date: "Mar 15", source: "Bloomberg", summary: "Lockheed Martin posted EPS of $6.21 vs. $6.48 consensus, citing supply-chain headwinds in its F-35 program.", sentiment: "bearish" },
      { title: "F-35 delivery delays raise program cost concerns", date: "Mar 12", source: "Wall Street Journal", summary: "USAF reports 15% delay in F-35 Block 4 deliveries, potentially adding $2B in overhead costs.", sentiment: "bearish" },
      { title: "LMT loses $4B satellite contract to rival", date: "Mar 10", source: "Defense News", summary: "Northrop Grumman wins JADC2 satellite link contract, shrinking LMT's space-sector backlog.", sentiment: "bearish" },
      { title: "Analyst downgrades LMT to Sell on margin risk", date: "Mar 8", source: "Morgan Stanley", summary: "MS cuts LMT target to $590, citing rising titanium costs and potential FARA program cancellation.", sentiment: "bearish" },
      { title: "LMT explores divesting IS&GS division", date: "Mar 5", source: "CNBC", summary: "Sources say Lockheed may sell its Information Systems unit to focus on core aeronautics.", sentiment: "neutral" },
    ],
  },
  {
    ticker: "CIEN", name: "Ciena Corporation", tradeType: "LONG", bullScore: 5, bearScore: 1, price: 82.00, rsi: 64.4,
    volumeRatio: 1.2, volumeSpike: false,
    signals: { sma200: true, sma50: true, rsiMomentum: true, volume: false, macd: true, priceAction: true, trendStrength: false, earningsSetup: false },
    entryAtr: 79.50, entryStructure: 80.50, bestEntry: 79.50, stopLoss: 75.00, target: 92.00, riskReward: 3.0, atr: 1.8, distance52w: 55.2,
    conflictTrend: true, earningsWarning: false, updatedAt: "11:01 PM ET",
    news: [
      { title: "Fiber optic demand rising on AI data-center buildout", date: "Mar 16", source: "Light Reading", summary: "Hyperscalers accelerating coherent optical upgrades; CIEN wins $220M AWS backbone deal.", sentiment: "bullish" },
      { title: "CIEN beats Q2 revenue by 7%, raises FY26 guidance", date: "Mar 13", source: "Bloomberg", summary: "Revenue came in at $1.12B, driven by strong Waveserver and Blue Planet software adoption.", sentiment: "bullish" },
      { title: "AT&T selects Ciena for open-line upgrades", date: "Mar 10", source: "Fierce Telecom", summary: "Multi-year contract covering 40,000 route-miles of long-haul network modernization.", sentiment: "bullish" },
      { title: "Supply-chain shortages ease for optical components", date: "Mar 8", source: "EE Times", summary: "Lead times for DSP chips fall from 52 to 28 weeks, improving CIEN's gross margin outlook.", sentiment: "bullish" },
      { title: "Competition intensifies from Infinera and Nokia", date: "Mar 5", source: "Dell'Oro Group", summary: "Optical networking market share battle heats up as Nokia slashes pricing on its PSE-3 platform.", sentiment: "bearish" },
      { title: "Ciena CFO sells $2M in shares at market highs", date: "Mar 2", source: "SEC Filing", summary: "CFO James Moylan liquidates 5,400 shares, raising insider selling total to $6M year-to-date.", sentiment: "bearish" },
    ],
  },
  {
    ticker: "FIX", name: "Comfort Systems USA", tradeType: "LONG", bullScore: 5, bearScore: 1, price: 342.00, rsi: 60.5,
    volumeRatio: 1.5, volumeSpike: false,
    signals: { sma200: true, sma50: true, rsiMomentum: true, volume: true, macd: true, priceAction: false, trendStrength: false, earningsSetup: false },
    entryAtr: 334.00, entryStructure: 337.00, bestEntry: 334.00, stopLoss: 318.00, target: 382.00, riskReward: 3.0, atr: 7.2, distance52w: 28.5,
    conflictTrend: true, earningsWarning: false, updatedAt: "11:01 PM ET",
    news: [
      { title: "FIX wins $350M data-center HVAC contract", date: "Mar 17", source: "PRNewswire", summary: "Comfort Systems secures a three-year mechanical and electrical scope for a major hyperscaler campus in Texas.", sentiment: "bullish" },
      { title: "Industrial construction backlog hits record $5.8B", date: "Mar 14", source: "Construction Dive", summary: "FIX's order backlog grew 18% YoY, underpinned by chip-fab and EV battery plant projects.", sentiment: "bullish" },
      { title: "FIX Q1 EPS beats consensus by 12%", date: "Mar 11", source: "Bloomberg", summary: "Adjusted EPS of $4.87 beat $4.34 estimate; margins expanded 80 bps on better project mix.", sentiment: "bullish" },
      { title: "Commercial HVAC replacement cycle accelerating", date: "Mar 9", source: "HPAC Engineering", summary: "Post-COVID IAQ mandates drive 20% surge in commercial HVAC retrofit demand nationwide.", sentiment: "bullish" },
      { title: "Labor shortages threaten FIX project timelines", date: "Mar 6", source: "ENR", summary: "Skilled trades shortage in Sun Belt markets could delay project completions and compress margins.", sentiment: "bearish" },
      { title: "Rising copper prices squeeze mechanical contractors", date: "Mar 3", source: "Metals Week", summary: "Copper at $4.80/lb adds $15M in annualized cost headwind for Comfort Systems' open projects.", sentiment: "bearish" },
    ],
  },
  {
    ticker: "MPC", name: "Marathon Petroleum Corp", tradeType: "LONG", bullScore: 5, bearScore: 2, price: 158.00, rsi: 61.9,
    volumeRatio: 1.4, volumeSpike: false,
    signals: { sma200: true, sma50: true, rsiMomentum: true, volume: false, macd: true, priceAction: true, trendStrength: false, earningsSetup: false },
    entryAtr: 154.00, entryStructure: 155.50, bestEntry: 154.00, stopLoss: 147.00, target: 177.00, riskReward: 3.29, atr: 3.0, distance52w: 12.8,
    conflictTrend: true, earningsWarning: false, updatedAt: "11:01 PM ET",
    news: [
      { title: "Crack spreads widen sharply, boosting refiner margins", date: "Mar 17", source: "S&P Global", summary: "3-2-1 crack spread reached $28.40/bbl as low gasoline inventories and rising demand converge.", sentiment: "bullish" },
      { title: "MPC repurchases $1.2B in shares during Q1", date: "Mar 14", source: "Bloomberg", summary: "Marathon continues aggressive capital return, buying back 5M shares at an average of $240/share.", sentiment: "bullish" },
      { title: "MPLX distributions raised 5% for Q2", date: "Mar 12", source: "PRNewswire", summary: "Midstream MLP subsidiary MPLX increases quarterly distribution, boosting MPC's cash flow visibility.", sentiment: "bullish" },
      { title: "Galveston Bay refinery completes major turnaround", date: "Mar 10", source: "Reuters", summary: "Largest US refinery returns to full 585,000 bbl/d capacity ahead of summer driving season.", sentiment: "bullish" },
      { title: "EPA renewable fuel standard compliance costs rise", date: "Mar 7", source: "Argus Media", summary: "RIN prices climb 40% YTD, adding an estimated $0.18/gallon headwind to refinery operating costs.", sentiment: "bearish" },
      { title: "Biofuel mandates threaten traditional refinery economics", date: "Mar 4", source: "E&E News", summary: "Proposed SAF blending requirements could require $800M in capital investment at MPC's facilities.", sentiment: "bearish" },
    ],
  },
  {
    ticker: "MU", name: "Micron Technology", tradeType: "LONG", bullScore: 6, bearScore: 1, price: 96.50, rsi: 60.8,
    volumeRatio: 1.5, volumeSpike: false,
    signals: { sma200: true, sma50: true, rsiMomentum: true, volume: true, macd: true, priceAction: true, trendStrength: false, earningsSetup: false },
    entryAtr: 93.00, entryStructure: 94.50, bestEntry: 93.00, stopLoss: 87.00, target: 112.00, riskReward: 3.16, atr: 2.8, distance52w: 15.4,
    conflictTrend: true, earningsWarning: false, updatedAt: "11:01 PM ET",
    news: [
      { title: "HBM3e demand surges for AI accelerator builds", date: "Mar 16", source: "AnandTech", summary: "Nvidia H200 and AMD MI350 adoption drives 3x YoY growth in Micron's high-bandwidth memory revenue.", sentiment: "bullish" },
      { title: "MU raises FQ3 guidance above Street consensus", date: "Mar 13", source: "Bloomberg", summary: "Data-center DRAM pricing improves 22% sequentially; EPS guidance of $1.58 tops $1.37 estimate.", sentiment: "bullish" },
      { title: "CHIPS Act grants $6.1B to Micron for Idaho fab", date: "Mar 10", source: "Commerce Dept", summary: "Federal funding unlocks $15B total investment for Boise manufacturing complex, adding 17,000 jobs.", sentiment: "bullish" },
      { title: "PC memory pricing recovers on inventory drawdown", date: "Mar 8", source: "DRAMeXchange", summary: "DDR5 contract prices rose 8% in March, signaling end of the two-year DRAM oversupply cycle.", sentiment: "bullish" },
      { title: "China export restrictions may cut MU revenue 10%", date: "Mar 5", source: "Reuters", summary: "BIS expands semiconductor restrictions, placing 14nm and below DRAM on Entity List for Chinese buyers.", sentiment: "bearish" },
      { title: "Samsung accelerates 1-beta DRAM ramp, pressuring pricing", date: "Mar 2", source: "The Elec", summary: "Korean giant targets 40% DRAM market share in 2H26, which analysts say will pressure ASPs.", sentiment: "bearish" },
    ],
  },
  {
    ticker: "AMAT", name: "Applied Materials Inc", tradeType: "LONG", bullScore: 5, bearScore: 2, price: 158.00, rsi: 61.3,
    volumeRatio: 0.9, volumeSpike: false,
    signals: { sma200: true, sma50: true, rsiMomentum: false, volume: false, macd: true, priceAction: true, trendStrength: true, earningsSetup: false },
    entryAtr: 154.00, entryStructure: 155.50, bestEntry: 154.00, stopLoss: 146.00, target: 177.00, riskReward: 2.88, atr: 3.5, distance52w: 4.8,
    conflictTrend: true, earningsWarning: false, updatedAt: "11:01 PM ET",
    news: [
      { title: "AMAT wins $2B gate-all-around tool order from TSMC", date: "Mar 16", source: "Nikkei Asia", summary: "Applied Materials secures multi-year contract for its Centura Sculpta etch tools for 2nm production.", sentiment: "bullish" },
      { title: "Services segment revenue grows 14% YoY", date: "Mar 13", source: "Bloomberg", summary: "High-margin AGS (Applied Global Services) unit reaches $1.5B quarterly revenue milestone.", sentiment: "bullish" },
      { title: "Semiconductor capex spending cycle expected to accelerate", date: "Mar 11", source: "Gartner", summary: "Foundry capex forecast raised to $210B for 2026, up 18% YoY, benefiting equipment vendors.", sentiment: "bullish" },
      { title: "AMAT partners with IMEC on 1.4Å process node research", date: "Mar 9", source: "SEMI", summary: "Joint research program aims to extend Moore's Law through novel dielectric deposition techniques.", sentiment: "bullish" },
      { title: "Export controls tighten on advanced etch equipment", date: "Mar 6", source: "Reuters", summary: "Commerce Department expands ECCN categories, restricting AMAT tool shipments to additional Chinese customers.", sentiment: "bearish" },
      { title: "Memory capex still subdued despite price recovery", date: "Mar 3", source: "Morgan Stanley", summary: "DRAM manufacturers withhold equipment orders pending further pricing stability, delaying AMAT's tool deliveries.", sentiment: "bearish" },
    ],
  },
  // ── Page 2 ──────────────────────────────────────────────────────────
  {
    ticker: "NVDA", name: "NVIDIA Corporation", tradeType: "LONG", bullScore: 7, bearScore: 1, price: 178.56, rsi: 65.4,
    volumeRatio: 2.1, volumeSpike: true,
    signals: { sma200: true, sma50: true, rsiMomentum: true, volume: true, macd: true, priceAction: true, trendStrength: true, earningsSetup: false },
    entryAtr: 174.00, entryStructure: 175.50, bestEntry: 174.00, stopLoss: 163.00, target: 205.00, riskReward: 3.09, atr: 4.2, distance52w: 28.4,
    conflictTrend: false, earningsWarning: false, updatedAt: "11:01 PM ET",
    news: [
      { title: "Blackwell GPU demand vastly exceeds supply through 2026", date: "Mar 17", source: "Bloomberg", summary: "TSMC CoWoS-L packaging bottleneck limits Blackwell output to 60% of hyperscaler orders; pricing premium widens.", sentiment: "bullish" },
      { title: "NVDA NIM microservices platform gains 3,000 enterprise customers", date: "Mar 14", source: "NVIDIA IR", summary: "AI software stack accelerates towards $1B ARR run-rate, strengthening software moat.", sentiment: "bullish" },
      { title: "US further restricts H20 exports to China", date: "Mar 11", source: "Reuters", summary: "New BIS rule bans H20 GPU shipments to Chinese cloud providers, removing ~$5B in projected FY27 revenue.", sentiment: "bearish" },
      { title: "Inference scaling laws favor NVDA's architecture", date: "Mar 9", source: "Semianalysis", summary: "Test-time compute trends benefit high-memory-bandwidth GPUs; NVDA's NVLink advantage widens vs competitors.", sentiment: "bullish" },
      { title: "AMD MI400 samples outperform expectations in MLPerf", date: "Mar 6", source: "AnandTech", summary: "AMD's next-gen accelerator narrows the training throughput gap with NVDA H100 by 22%.", sentiment: "bearish" },
      { title: "NVDA announces $500B US manufacturing partnership with TSMC", date: "Mar 3", source: "White House", summary: "Joint fab investment commits 30% of advanced GPU production to US-based CoWoS facilities by 2028.", sentiment: "bullish" },
    ],
  },
  {
    ticker: "META", name: "Meta Platforms Inc", tradeType: "LONG", bullScore: 6, bearScore: 1, price: 588.00, rsi: 63.5,
    volumeRatio: 1.6, volumeSpike: false,
    signals: { sma200: true, sma50: true, rsiMomentum: true, volume: true, macd: true, priceAction: true, trendStrength: false, earningsSetup: false },
    entryAtr: 582.00, entryStructure: 585.00, bestEntry: 582.00, stopLoss: 565.00, target: 640.00, riskReward: 3.41, atr: 8.3, distance52w: 98.7,
    conflictTrend: false, earningsWarning: false, updatedAt: "11:01 PM ET",
    news: [
      { title: "Meta's ad revenue accelerates on Llama-powered targeting", date: "Mar 17", source: "Bloomberg", summary: "AI-optimized ad ranking improves CTR by 18% for SMB advertisers, fueling outperformance vs. peers.", sentiment: "bullish" },
      { title: "Threads crosses 350M MAU, rivaling X for ad dollars", date: "Mar 14", source: "TechCrunch", summary: "Advertiser interest in brand-safe environment drives CPM premium over Twitter/X alternatives.", sentiment: "bullish" },
      { title: "EU Digital Markets Act compliance costs top $1.2B", date: "Mar 11", source: "FT", summary: "Interoperability mandates require significant API engineering and increase moderation overhead.", sentiment: "bearish" },
      { title: "Reality Labs losses widen to $5B in Q4", date: "Mar 9", source: "Reuters", summary: "AR glasses ramp slower than expected; headset category revenue flat despite Quest 3S launch.", sentiment: "bearish" },
      { title: "META raises 2026 capex guidance to $65B for AI infra", date: "Mar 7", source: "CNBC", summary: "Zuckerberg commits to building out AI superintelligence infrastructure, raising investor capex concerns.", sentiment: "neutral" },
      { title: "Instagram Reels monetization rate approaches YouTube levels", date: "Mar 4", source: "Insider Intelligence", summary: "Short-form video RPM reaches $8.40, narrowing the gap with YouTube's $12 benchmark.", sentiment: "bullish" },
    ],
  },
  {
    ticker: "TSLA", name: "Tesla Inc", tradeType: "SHORT", bullScore: 2, bearScore: 6, price: 245.00, rsi: 38.7,
    volumeRatio: 2.3, volumeSpike: true,
    signals: { sma200: true, sma50: true, rsiMomentum: true, volume: true, macd: true, priceAction: false, trendStrength: true, earningsSetup: false },
    entryAtr: 242.00, entryStructure: 241.00, bestEntry: 242.00, stopLoss: 255.00, target: 210.00, riskReward: 2.46, atr: 7.8, distance52w: -42.3,
    conflictTrend: false, earningsWarning: false, updatedAt: "11:01 PM ET",
    news: [
      { title: "Tesla Q1 deliveries miss by 18%, lowest since 2022", date: "Mar 17", source: "Bloomberg", summary: "Q1 deliveries of 336,000 units fell far short of 411,000 analyst consensus, citing Cybertruck recall and EU sales slump.", sentiment: "bearish" },
      { title: "European market share falls to 9.8% on BYD competition", date: "Mar 14", source: "European Automobile Manufacturers Assoc", summary: "EU EV registrations show TSLA losing 4 points of market share as Chinese brands undercut pricing.", sentiment: "bearish" },
      { title: "Musk political activity continues to weigh on brand perception", date: "Mar 11", source: "Reuters", summary: "Consumer boycott campaigns grow in EU and US; dealership foot traffic tracking tools report 15% drop.", sentiment: "bearish" },
      { title: "FSD v13 achieves zero driver interventions on 1,000-mile test", date: "Mar 9", source: "Electrek", summary: "Latest full self-driving release shows marked improvement; potential regulatory green light in AZ and TX.", sentiment: "bullish" },
      { title: "Tesla Energy storage deployments up 130% YoY", date: "Mar 7", source: "PRNewswire", summary: "Megapack orders surge as utilities prioritize grid-scale batteries; this segment now 20% of gross profit.", sentiment: "bullish" },
      { title: "CEO compensation controversy sparks shareholder activism", date: "Mar 4", source: "Wall Street Journal", summary: "ISS recommends withholding votes for three Tesla board members over re-approval of $56B pay package.", sentiment: "bearish" },
    ],
  },
  {
    ticker: "AMZN", name: "Amazon.com Inc", tradeType: "LONG", bullScore: 6, bearScore: 1, price: 208.00, rsi: 59.8,
    volumeRatio: 1.2, volumeSpike: false,
    signals: { sma200: true, sma50: true, rsiMomentum: true, volume: false, macd: true, priceAction: true, trendStrength: true, earningsSetup: false },
    entryAtr: 203.00, entryStructure: 204.50, bestEntry: 203.00, stopLoss: 195.00, target: 232.00, riskReward: 3.63, atr: 4.2, distance52w: 38.6,
    conflictTrend: false, earningsWarning: false, updatedAt: "11:01 PM ET",
    news: [
      { title: "AWS revenue accelerates to 22% YoY growth in Q4", date: "Mar 16", source: "Amazon IR", summary: "Cloud segment hits $107B annualized revenue run-rate, driven by generative AI workload migration.", sentiment: "bullish" },
      { title: "Amazon advertising exceeds $60B annualized revenue", date: "Mar 13", source: "Bloomberg", summary: "Sponsored Products and DSP growth rate of 28% YoY outpaces Google and Meta in same period.", sentiment: "bullish" },
      { title: "FTC antitrust probe into Prime bundling expands", date: "Mar 10", source: "Reuters", summary: "Regulators investigating whether Prime membership tying harms marketplace competition; trial set for 2027.", sentiment: "bearish" },
      { title: "Project Kuiper launches first 100 production satellites", date: "Mar 8", source: "SpaceNews", summary: "Amazon's broadband constellation begins commercial beta service; targets 3,236-satellite LEO network by end-2026.", sentiment: "bullish" },
      { title: "Amazon fulfillment automation cuts costs 20%", date: "Mar 6", source: "Supply Chain Dive", summary: "Sequoia robotics system deployed in 25 FC sites reduces per-unit fulfillment cost from $3.80 to $3.05.", sentiment: "bullish" },
      { title: "EU digital services act compliance adding $2B in costs", date: "Mar 3", source: "FT", summary: "Marketplace content moderation obligations require 5,000 new EU-based trust & safety headcount.", sentiment: "bearish" },
    ],
  },
  {
    ticker: "MSFT", name: "Microsoft Corporation", tradeType: "LONG", bullScore: 6, bearScore: 1, price: 418.00, rsi: 57.3,
    volumeRatio: 0.9, volumeSpike: false,
    signals: { sma200: true, sma50: true, rsiMomentum: true, volume: false, macd: true, priceAction: true, trendStrength: true, earningsSetup: false },
    entryAtr: 410.00, entryStructure: 412.50, bestEntry: 410.00, stopLoss: 396.00, target: 450.00, riskReward: 2.86, atr: 5.8, distance52w: 8.2,
    conflictTrend: false, earningsWarning: false, updatedAt: "11:01 PM ET",
    news: [
      { title: "Copilot+ PC adoption rate reaches 30% of new Windows sales", date: "Mar 17", source: "IDC", summary: "NPU-powered AI features driving premium PC refresh cycle; MSFT ASP rises $180 on Copilot SKU attach.", sentiment: "bullish" },
      { title: "Azure OpenAI Service now used by 65% of Fortune 500", date: "Mar 14", source: "Microsoft IR", summary: "Enterprise AI adoption accelerates with Azure AI Foundry onboarding 3,000 new customers in Q1.", sentiment: "bullish" },
      { title: "GitHub Copilot Enterprise ARR exceeds $2B", date: "Mar 12", source: "Bloomberg", summary: "Developer productivity tool sees 200% YoY revenue growth as enterprises expand seat counts.", sentiment: "bullish" },
      { title: "Activision integration costs trim EPS by $0.22 in FY26", date: "Mar 9", source: "Reuters", summary: "Game studio restructuring charges and goodwill amortization weigh on reported earnings.", sentiment: "bearish" },
      { title: "DOJ launches fresh antitrust inquiry into Teams bundling", date: "Mar 7", source: "Wall Street Journal", summary: "Department of Justice opens investigation into whether Teams is illegally tied to Microsoft 365 subscriptions.", sentiment: "bearish" },
      { title: "MSFT raises dividend 10% and authorizes $60B buyback", date: "Apr 13", source: "PRNewswire", summary: "Board increases quarterly dividend to $0.83/share and extends capital return authorization to 2028.", sentiment: "bullish" },
    ],
  },
  {
    ticker: "AAPL", name: "Apple Inc", tradeType: "LONG", bullScore: 5, bearScore: 2, price: 212.00, rsi: 56.4,
    volumeRatio: 1.1, volumeSpike: false,
    signals: { sma200: true, sma50: true, rsiMomentum: true, volume: false, macd: true, priceAction: true, trendStrength: false, earningsSetup: false },
    entryAtr: 207.00, entryStructure: 208.50, bestEntry: 207.00, stopLoss: 198.00, target: 235.00, riskReward: 3.11, atr: 3.4, distance52w: 18.6,
    conflictTrend: true, earningsWarning: false, updatedAt: "4:15 PM ET",
    news: [
      { title: "Apple Intelligence features drive iPhone 16 upgrade cycle", date: "Apr 28", source: "IDC", summary: "AI-enabled on-device features push upgrade rate to 18% vs. 14% cycle average; replacement accelerating.", sentiment: "bullish" },
      { title: "App Store services revenue hits $100B annualized run-rate", date: "Apr 25", source: "Apple IR", summary: "Subscriptions, payments and licensing hit key milestone; services now 26% of total revenue.", sentiment: "bullish" },
      { title: "Apple Vision Pro 2 enters mass production for holiday 2025", date: "Apr 22", source: "The Information", summary: "Next-gen spatial computing device targets $2,499 price point; supply chain gearing for 2M unit launch.", sentiment: "bullish" },
      { title: "India manufacturing reaches 20% of global iPhone output", date: "Apr 19", source: "Bloomberg", summary: "Foxconn and Tata achieve production quality parity with China facilities; tariff diversification complete.", sentiment: "bullish" },
      { title: "EU demands Apple open NFC chip to rivals under DMA", date: "Apr 16", source: "Reuters", summary: "European Commission demands NFC tap-to-pay access for competing platforms, threatening Apple Pay exclusivity.", sentiment: "bearish" },
      { title: "China iPhone sales decline 11% amid Huawei resurgence", date: "Apr 13", source: "IDC China", summary: "Mate 70 and Magic V3 recapture premium Chinese buyers; AAPL China revenue down $2.1B YoY.", sentiment: "bearish" },
    ],
  },
  {
    ticker: "GE", name: "GE Aerospace", tradeType: "LONG", bullScore: 6, bearScore: 1, price: 220.00, rsi: 61.8,
    volumeRatio: 1.4, volumeSpike: false,
    signals: { sma200: true, sma50: true, rsiMomentum: true, volume: false, macd: true, priceAction: true, trendStrength: true, earningsSetup: false },
    entryAtr: 215.00, entryStructure: 216.50, bestEntry: 215.00, stopLoss: 203.00, target: 248.00, riskReward: 3.00, atr: 4.5, distance52w: 42.8,
    conflictTrend: false, earningsWarning: false, updatedAt: "4:15 PM ET",
    news: [
      { title: "GE Aerospace Q1 EPS beats by 18%; raises FY2025 guidance", date: "Apr 22", source: "GE IR", summary: "Reported EPS of $1.49 vs. $1.26 consensus; services revenue up 14% YoY on engine overhaul demand.", sentiment: "bullish" },
      { title: "LEAP engine backlog reaches record 14,000 units", date: "Apr 19", source: "Aviation Week", summary: "Boeing 737 MAX and Airbus A320neo demand drives LEAP order acceleration; 2026-2028 slots now filled.", sentiment: "bullish" },
      { title: "GE wins $3.5B US Air Force T-7A trainer engine contract", date: "Apr 16", source: "Defense News", summary: "F414 derivative engines secure multi-decade revenue stream; production begins at Lynn, MA facility.", sentiment: "bullish" },
      { title: "Global air travel reaches 115% of 2019 levels; MRO demand surges", date: "Apr 13", source: "IATA", summary: "Pent-up fleet renewal and record RPM drive GE's services backlog to $122B, all-time high.", sentiment: "bullish" },
      { title: "Supply-chain delays at Spirit AeroSystems affect MAX engine deliveries", date: "Apr 10", source: "Reuters", summary: "Fuselage shortages slow final assembly; GE must hold 280 completed LEAP engines in quarantine.", sentiment: "bearish" },
      { title: "Titanium sourcing shift from Russia adds $180M in costs for 2025", date: "Apr 7", source: "Bloomberg", summary: "Post-sanctions requalification of non-Russian titanium alloys requires costly re-certification processes.", sentiment: "bearish" },
    ],
  },
  {
    ticker: "FDX", name: "FedEx Corporation", tradeType: "LONG", bullScore: 5, bearScore: 2, price: 260.00, rsi: 57.2,
    volumeRatio: 1.2, volumeSpike: false,
    signals: { sma200: true, sma50: true, rsiMomentum: true, volume: false, macd: true, priceAction: true, trendStrength: false, earningsSetup: false },
    entryAtr: 254.00, entryStructure: 256.00, bestEntry: 254.00, stopLoss: 241.00, target: 291.00, riskReward: 2.69, atr: 5.8, distance52w: 10.2,
    conflictTrend: true, earningsWarning: false, updatedAt: "4:15 PM ET",
    news: [
      { title: "FedEx Q3 beats estimates; raises DRIVE program savings to $4B", date: "Apr 29", source: "Bloomberg", summary: "Adj. EPS of $4.51 tops $4.16; efficiency program delivers $800M ahead of schedule via network consolidation.", sentiment: "bullish" },
      { title: "FDX network integration saves $200M/quarter from route rationalization", date: "Apr 26", source: "Transport Topics", summary: "Express and Ground merger complete; 40 hub closures reduce daily line-haul trips by 18%.", sentiment: "bullish" },
      { title: "FedEx signs 5-year UPS-displacement contract with PepsiCo", date: "Apr 23", source: "Reuters", summary: "FDX secures preferred ground parcel carrier deal for Pepsi's 850+ US distribution centers.", sentiment: "bullish" },
      { title: "E-commerce parcel volume rebounds 11% YoY in Q3", date: "Apr 20", source: "Shipbob", summary: "Return-to-growth in B2C parcel after 2-year correction improves FDX's Ground network utilization.", sentiment: "bullish" },
      { title: "Fuel surcharge revenue declines as jet fuel falls to $2.45/gal", date: "Apr 17", source: "S&P Global", summary: "Lower fuel surcharges add yield pressure even as volume recovers; FDX Express margin guidance trimmed 40bps.", sentiment: "bearish" },
      { title: "Amazon in-house delivery now handles 75% of its own parcels", date: "Apr 14", source: "Wall Street Journal", summary: "Amazon Logistics handles 75% of Amazon Prime volume, down from 100% FedEx share in 2018.", sentiment: "bearish" },
    ],
  },
  {
    ticker: "GOOGL", name: "Alphabet Inc", tradeType: "LONG", bullScore: 5, bearScore: 2, price: 175.00, rsi: 55.6,
    volumeRatio: 1.1, volumeSpike: false,
    signals: { sma200: true, sma50: true, rsiMomentum: true, volume: false, macd: true, priceAction: true, trendStrength: false, earningsSetup: false },
    entryAtr: 171.00, entryStructure: 172.50, bestEntry: 171.00, stopLoss: 163.00, target: 196.00, riskReward: 3.13, atr: 3.2, distance52w: 22.4,
    conflictTrend: false, earningsWarning: false, updatedAt: "4:15 PM ET",
    news: [
      { title: "Google Search AI Overviews reach 1.5B users globally", date: "Apr 28", source: "Bloomberg", summary: "Gemini-powered search features increase session length by 12% and ad impression frequency.", sentiment: "bullish" },
      { title: "YouTube Shorts monetization gap with TikTok narrows significantly", date: "Apr 25", source: "Insider Intelligence", summary: "Short-form RPM rises to $7.20 from $5.50 YoY as Google improves creator revenue share and brand targeting.", sentiment: "bullish" },
      { title: "DOJ proposes breakup of Google Ad Tech stack", date: "Apr 22", source: "Reuters", summary: "Remedies trial recommends forcing Alphabet to divest DFP ad server and AdX exchange, removing key revenue.", sentiment: "bearish" },
      { title: "Waymo One rides surpass 250,000 per week in major US cities", date: "Apr 19", source: "TechCrunch", summary: "Robotaxi service expands to Atlanta and Miami; revenue run-rate approaches $500M annualized.", sentiment: "bullish" },
      { title: "Gemini Ultra 2.0 outperforms GPT-5 on key reasoning benchmarks", date: "Apr 16", source: "Ars Technica", summary: "MMLU and GPQA scores show Google closing the gap with OpenAI on enterprise reasoning tasks.", sentiment: "bullish" },
      { title: "Apple threatens to remove Google as default search on iOS", date: "Apr 13", source: "Wall Street Journal", summary: "Cupertino explores Perplexity and Gemini as alternative defaults; potential loss of $18B TAC revenue.", sentiment: "bearish" },
    ],
  },
];

export const mockScoreHistory: Record<string, { bull: number; bear: number; date: string }[]> = {
  NVDA: [
    { bull: 5, bear: 1, date: "Apr 22" }, { bull: 6, bear: 1, date: "Apr 23" }, { bull: 6, bear: 1, date: "Apr 24" },
    { bull: 7, bear: 1, date: "Apr 25" }, { bull: 7, bear: 1, date: "Apr 26" }, { bull: 7, bear: 1, date: "Apr 27" },
    { bull: 7, bear: 1, date: "Apr 28" }, { bull: 7, bear: 1, date: "Apr 29" },
  ],
  TSLA: [
    { bull: 4, bear: 3, date: "Apr 22" }, { bull: 3, bear: 4, date: "Apr 23" }, { bull: 3, bear: 4, date: "Apr 24" },
    { bull: 2, bear: 5, date: "Apr 25" }, { bull: 2, bear: 5, date: "Apr 26" }, { bull: 2, bear: 6, date: "Apr 27" },
    { bull: 2, bear: 6, date: "Apr 28" }, { bull: 2, bear: 6, date: "Apr 29" },
  ],
  LMT: [
    { bull: 3, bear: 4, date: "Apr 22" }, { bull: 2, bear: 5, date: "Apr 23" }, { bull: 2, bear: 5, date: "Apr 24" },
    { bull: 2, bear: 6, date: "Apr 25" }, { bull: 2, bear: 6, date: "Apr 26" }, { bull: 2, bear: 7, date: "Apr 27" },
    { bull: 2, bear: 7, date: "Apr 28" }, { bull: 2, bear: 7, date: "Apr 29" },
  ],
  SOFI: [
    { bull: 4, bear: 2, date: "Apr 22" }, { bull: 4, bear: 2, date: "Apr 23" }, { bull: 5, bear: 2, date: "Apr 24" },
    { bull: 5, bear: 2, date: "Apr 25" }, { bull: 5, bear: 2, date: "Apr 26" }, { bull: 6, bear: 2, date: "Apr 27" },
    { bull: 6, bear: 2, date: "Apr 28" }, { bull: 6, bear: 2, date: "Apr 29" },
  ],
  CIEN: [
    { bull: 3, bear: 1, date: "Apr 22" }, { bull: 3, bear: 1, date: "Apr 23" }, { bull: 4, bear: 1, date: "Apr 24" },
    { bull: 4, bear: 1, date: "Apr 25" }, { bull: 5, bear: 1, date: "Apr 26" }, { bull: 5, bear: 1, date: "Apr 27" },
    { bull: 5, bear: 1, date: "Apr 28" }, { bull: 5, bear: 1, date: "Apr 29" },
  ],
  MARA: [
    { bull: 3, bear: 3, date: "Apr 22" }, { bull: 3, bear: 3, date: "Apr 23" }, { bull: 4, bear: 3, date: "Apr 24" },
    { bull: 4, bear: 3, date: "Apr 25" }, { bull: 5, bear: 3, date: "Apr 26" }, { bull: 5, bear: 3, date: "Apr 27" },
    { bull: 5, bear: 3, date: "Apr 28" }, { bull: 5, bear: 3, date: "Apr 29" },
  ],
};

export const lastRunInfo = {
  timestamp: "Apr 29 4:15 PM",
  stockCount: 25,
  regime: "BEARISH" as const,
  runId: "swingpulse-2025-0429",
  universe: "SwingPulse 25 — v1.0",
};
